config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  resources :microposts

  

  get 'users/new'

  resources :users 

  root 'static_pages#home'

  get 'help' => 'static_pages#help'
       
  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :microposts, only: [:create, :destroy]

  get 'like' => 'microposts#like'
  get 'unlike' => 'microposts#unlike'

  

  resources :comments, only: [:create, :destroy]

  get 'commentlike' => 'comments#commentlike'
  get 'commentunlike' => 'comments#commentunlike'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  has_many :likes
  has_many :comments, :as => :comment
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate :picture_size

  private

   def picture_size
   	  if picture.size > 5.megabytes
   	 	  errors.add(:picture, "should be less than 5MB")
   	  end
   	end 	
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  # http_basic_authenticate_with :name => "dhh", :password => "secret", :only => :destroy
  # before_action :authenticate_user!
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def index
    @microposts = Micropost.all
     @comment = @micropost.comments.build(params[:comment])
     @comment.user = current_user
  end  
  
  def create
  	 @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      logger.debug Micropost.all
      flash[:success] = "Micropost created!"
      redirect_to root_url
  	else
      @feed_items = []
  	  render 'static_pages/home'
  	end  	  	
  end
  
  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  def comments_count
    comment.count
  end

  def like
      @like = Like.new()
      @like.micropost_id = params[:micropost_id]
      if @like.save
        redirect_to root_url
      end         
  end  
  
  def unlike
      @like = Like.find_by(micropost_id: params[:micropost_id])
      if @like.delete
        redirect_to root_url
      end  
  end 

  private

    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>

      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

  <span><a class="like-Unlike" href="micropost_id">Like</a></span>
<script>
function LikeUnLikeButton() {
            $(".like-Unlike").click(function (e) {
                if ($(this).html() == "Like") {
                    $(this).html('Unlike');
                }
                else {
                    $(this).html('Like');
                }
            });
        }
LikeUnLikeButton();
</script>
<% end %>

app/views/microposts/_like.html.erb
<span><a class="like-Unlike" href="#">Like</a></span>
<script>
function LikeUnLikeButton() {
            $(".like-Unlike").click(function (e) {
                if ($(this).html() == "Like") {
                    $(this).html('Unlike');
                }
                else {
                    $(this).html('Like');
                }
            });
        }
LikeUnLikeButton();
</script>
<!-- <sapn><a class="like-Unlike" href="#">Like</a></sapn> -->
<!--<script> 
// function like(micropost_id,user_id,default_count)
// {
//   if( user_id == 0 ) {
//     jQuery("#show_login_box").fancybox({cyclic: true}).trigger('click');
//   } else {
//            if( default_count == 0 ) {
//              var new_count = '1';
//              var link = 'unlike(\'' + micropost_id + '\',\'' + user_id + '\',\'' + new_count + '\')\;';
//              jQuery('.likes').html('You like this.');
//             } else {
//              var new_count = parseInt(default_count) + 1;
//                if ( jQuery('.like-user').length ) {
//                    var name = jQuery('.like-user').html();
//                    var link = 'unlike(\'' + micropost_id + '\',\'' + user_id + '\',\'' + new_count + '\')\;';
//                    jQuery('.likes').html('You and <span class="like-user">'  + name + '</span> likes this.');

//                } else {
//                    var link = 'unlike(\'' + micropost_id + '\',\'' + user_id + '\',\'' + new_count + '\')\;';
//                    jQuery('.likes').html('You and <span class="like-user"><a href="#">'  + default_count + ' others</a></span> like this.');

//                }
//             }
//              jQuery('.like_click').attr('onclick',link);
//              jQuery('.like_click span').html('Unlike');
//     jQuery.ajax({
//         url: "/like",
//         // type: 'POST',
//         data: { mcriopost_id: micropost_id, user_id: user_id, type: 'like', count: default_count },
//         // dataType: 'json', 
//         success: function(data)
//         {
//              // jQuery('#' + object_id + '_count').html(data.total);
//         }
//     });
//   }
// }
</script> -->

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to "Delete", micropost, method: :delete, data: { confirm: "You sure?" } %>
    <% end %>
    <% like = Like.find_by(micropost_id: micropost.id)%>
      <% if like.nil? %>
         <span><a id="like-Unlike_<%= micropost.id %>" href="#" onclick="LikeUnLikeButton(<%= micropost.id %>
      )">Like</a></span>
      <%else%> 
         <span><a id="like-Unlike_<%= micropost.id %>" href="#" onclick="LikeUnLikeButton(<%= micropost.id %>
      )">Unlike</a></span>
      <%end%>
      <%= render 'comments/comment', micropost: micropost  %>
  </span>

  <script>
    function LikeUnLikeButton(micropost_id) {
                
                    if ($("#like-Unlike_"+micropost_id).html() == "Like") {
                        $("#like-Unlike_"+micropost_id).html('Unlike');
                           $.ajax({
                                     url: "/like",
                                     data: {micropost_id: micropost_id},
                                     success: function(data) {
                                         // ... do stuff here
                                     }
                                 });
                    }
                    else {
                        $("#like-Unlike_"+micropost_id).html('Like');
                        $.ajax({
                                     url: "/unlike",
                                     data: {micropost_id: micropost_id},
                                     success: function(data) {
                                         // ... do stuff here
                                     }
                                 });
                    
                }
            }
</script>    

app/views/microposts/_unlike.html.erb
<%= form_for(current_user.appreciations.find_by_liked_id(@post), 
                               :html => { :method => :delete },
                               :remote => true) do |f| %>
<div class="actions"><%#= f.submit "Unlike" %></div>
<% end %>
 
 <!-- <sapn><a class="like-Unlike" href="#">Like</a></sapn>
<script> 
 function unlike(,micropost_id,user_id,default_count)
{
            if( default_count == 1 ) {
             var new_count= '0';
             var link = 'like(\'' + micropost_id + '\',\'' + user_id + '\',\'' + default_count + '\',\'' + not_like + '\')\;';
             jQuery('.likes').html('');
            } else {
             var new_count = parseInt(default_count) - 1;
               if ( jQuery('.like-user').length  && default_count > 1 ) {
                   var name = jQuery('.like-user').html();
                   var link = 'like(\'' + micropost_id + '\',\'' + user_id + '\',\'' + new_count + '\')\;';
                   jQuery('.likes').html('<span class="like-user">'  + name + '</span> like this.');

               } else {
                   var link = 'like(\'' + micropost_id + '\',\'' + user_id + '\',\'' + new_count + '\')\;';
                   jQuery('.likes').html('<span class="like-user"><a href="#">'  + new_count + ' people</a></span> like this.');

               }
            }
             jQuery('.like_click').attr('onclick',link);
             jQuery('.like_click span').html('Like');
    jQuery.ajax({
        url: "/unlike",
        // type: 'POST',
        data: { micropost_id: micropost_id, user_id: user_id, type: 'unlike', count: default_count },
        dataType: 'json', 
        success: function(data)
        {
             // jQuery('#' + object_id + '_count').html(data.total);
        }
    });
}
</script> -->

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.comments.count %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<h2>Comments</h2>
<%= render @micropost.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>

<br />

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>